const all = [
  {
    id: 1,
    name: "Goodthreads Women's High-Rise Skinny Jean",
    price: "40.00",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/81Jnc53FoOL._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71IOzFZqtbL._AC_UL320_.jpg",
        color: "brown",
      },
    ],
    solde: true,
    old_price: "150.42",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["white", "brown"],
    gender: "women",
  },
  {
    id: 2,
    name: "Goodthreads Men's Slim-Fit Selvedge Jean",
    price: "142.32",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/811224LsH9L._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71KC4pgEtxL._AC_UL320_.jpg",
        color: "black",
      },
    ],
    solde: false,
    old_price: "",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["blue", "black"],
    gender: "men",
  },
  {
    id: 3,
    name: "Levi's Men's 501 Original Fit Jeans",
    price: "30.45",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/51WBk2gSIjL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/91GXtYlzJWL._AC_UL320_.jpg",
        color: "gray",
      },
      {
        image: "https://m.media-amazon.com/images/I/61UWxmo1bgL._AC_UL320_.jpg",
        color: "blue",
      },
    ],
    solde: true,
    old_price: "78.23",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["black", "gray", "blue"],
    gender: "men",
  },
  {
    id: 4,
    name: "Daily Ritual Women's High-Rise Skinny Jean",
    price: "48.14",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/81RDUDeClLL._AC_UL320_.jpg",
        color: "gray",
      },
      {
        image: "https://m.media-amazon.com/images/I/81UwxTpG-oL._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71ImcTG+wAL._AC_UL320_.jpg",
        color: "black",
      },
    ],
    solde: true,
    old_price: "143",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["gray", "blue", "black"],
    gender: "women",
  },
  {
    id: 5,
    name: "American Apparel Women's High-Waist Jean",
    price: "123",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71y6LE5Xp-L._AC_UL320_.jpg",
        color: "blue",
      },
    ],
    solde: false,
    old_price: "",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["blue"],
    gender: "women",
  },
  {
    id: 6,
    name: "adidas Men's Grand Court Sneaker",
    price: "147.26",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/41d6LOJTMTL._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71+ndfCKGUL._AC_UL320_.jpg",
        color: "gray",
      },
      {
        image: "https://m.media-amazon.com/images/I/71eQ+FDlBPL._AC_UL320_.jpg",
        color: "white",
      },
    ],
    solde: true,
    old_price: "200",
    sizes: ["3", "5", "8"],
    colors: ["blue", "gray", "white"],
    gender: "men",
  },
  {
    id: 7,
    name: "Skechers Work Cessnock",
    price: "100.00",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71k4rWgqrHL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/61sHA7o-bxL._AC_UL320_.jpg",
        color: "purple",
      },
    ],
    solde: false,
    old_price: "",
    sizes: ["3", "5", "8"],
    colors: ["black", "purple"],
    gender: "men",
  },
  {
    id: 8,
    name: "Converse Chuck Taylor All Star Low Top",
    price: "65.60",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71BqXmSHK2L._AC_UL320_.jpg",
        color: "white",
      },
    ],
    solde: false,
    old_price: "",
    sizes: ["3", "5", "8"],
    colors: ["white"],
    gender: "women",
  },
  {
    id: 9,
    name: "PUMA Women's Carina Sneaker",
    price: "105.01",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71FfObARk-L._AC_UL320_.jpg",
        color: "white",
      },
      {
        image: "https://m.media-amazon.com/images/I/61PgrIs5NQL._AC_UL320_.jpg",
        color: "black",
      },
    ],
    solde: false,
    old_price: "",
    sizes: ["3", "5", "8"],
    colors: ["white", "black"],
    gender: "women",
  },
  {
    id: 10,
    name: "Gildan Men's G2000 Ultra Cotton Adult T-Shirt",
    price: "14",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71a82Qa+vnL._AC_UL320_.jpg",
        color: "orange",
      },
      {
        image: "https://m.media-amazon.com/images/I/81lOBK9li-L._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/81IqOH5pkrL._AC_UL320_.jpg",
        color: "white",
      },
    ],
    solde: true,
    old_price: "20.22",
    sizes: ["m", "l", "xl"],
    colors: ["orange", "black", "white"],
    gender: "men",
  },
  {
    id: 11,
    name: "Under Armour Men's Tech 2.0 Short Sleeve T-Shirt",
    price: "19.20",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/81FPcR64ClL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/51lP-QfwSYL._AC_UL320_.jpg",
        color: "pink",
      },
    ],
    solde: true,
    old_price: "30.14",
    sizes: ["m", "l", "xl"],
    colors: ["black", "pink"],
    gender: "men",
  },
  {
    id: 12,
    name: "Hanes Sport Women's Cool DRI Performance V-Neck Tee",
    price: "30",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/81gNC0hPf0L._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/71pYGdc-ujL._AC_UL320_.jpg",
        color: "white",
      },
      {
        image: "https://m.media-amazon.com/images/I/71kTIUzW5gL._AC_UL320_.jpg",
        color: "yellow",
      }
    ],
    solde: false,
    old_price: "",
    sizes: ["m", "l", "xl"],
    colors: ["black", "white", "yellow"],
    gender: "women",
  },
  {
    id: 13,
    name: "Be Kind T Shirts Women Cute Graphic Blessed Shirt Funny ",
    price: "40.44",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/61xyGKwt0SL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/71nCGNtDe1L._AC_UL320_.jpg",
        color: "yellow",
      },
      {
        image: "https://m.media-amazon.com/images/I/61cjJpv1gHL._AC_UL320_.jpg",
        color: "brown",
      },
    ],
    solde: true,
    old_price: "100.22",
    sizes: ["m", "l", "xl"],
    colors: ["black", "yellow", "brown"],
    gender: "women",
  },
  {
    id: 14,
    name: "Donerton Smart Watch",
    price: "15.32",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/617aPQkNYHL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/8111yj0YDBL._AC_UL320_.jpg",
        color: "white",
      },
      {
        image: "https://m.media-amazon.com/images/I/91EgExdxyNL._AC_UL320_.jpg",
        color: "brown",
      },
    ],
    solde: false,
    old_price: "",
    colors: ["black", "white", "brown"],
    gender: "women",
  },
  {
    id: 15,
    name: "Mens Watches Mechanical Automatic Self-Winding",
    price: "60.15",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71RSNEqQjtL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/71E4HTIrUNL._AC_UL320_.jpg",
        color: "white",
      },
      {
        image: "https://m.media-amazon.com/images/I/711dIHD599L._AC_UL320_.jpg",
        color: "gold",
      },
    ],
    solde: true,
    old_price: "99.99",
    colors: ["black", "white", "gold"],
    gender: "women",
  },
  {
    id: 16,
    name: "Fitbit Versa 2 Health and Fitness Smartwatch with Heart Rate",
    price: "30.35",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/61JzeOC9rsL._AC_UL320_.jpg",
        color: "white",
      },
      {
        image: "https://m.media-amazon.com/images/I/61uyt0TfoEL._AC_UL320_.jpg",
        color: "black",
      },
    ],
    solde: true,
    old_price: "70.48",
    colors: ["white", "black"],
    gender: "men",
  },
  {
    id: 17,
    name: "Samsung Galaxy Watch ",
    price: "145.15",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71uveJVT5IL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/61Z5SWOkJZL._AC_UL320_.jpg",
        color: "gold",
      },
    ],
    solde: false,
    old_price: "",
    colors: ["black", "gold"],
    gender: "men",
  },
];

export default all;
