// Watches
const jeans = [
  {
    id: 1,
    name: "Goodthreads Women's High-Rise Skinny Jean",
    price: "40.00",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/81Jnc53FoOL._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71IOzFZqtbL._AC_UL320_.jpg",
        color: "brown",
      },
    ],
    solde: true,
    old_price: "150.42",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["white", "brown"],
    gender: "women",
  },
  {
    id: 2,
    name: "Goodthreads Men's Slim-Fit Selvedge Jean",
    price: "142.32",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/811224LsH9L._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71KC4pgEtxL._AC_UL320_.jpg",
        color: "black",
      },
    ],
    solde: false,
    old_price: "",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["blue", "black"],
    gender: "men",
  },
  {
    id: 3,
    name: "Levi's Men's 501 Original Fit Jeans",
    price: "30.45",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/51WBk2gSIjL._AC_UL320_.jpg",
        color: "black",
      },
      {
        image: "https://m.media-amazon.com/images/I/91GXtYlzJWL._AC_UL320_.jpg",
        color: "gray",
      },
      {
        image: "https://m.media-amazon.com/images/I/61UWxmo1bgL._AC_UL320_.jpg",
        color: "blue",
      },
    ],
    solde: true,
    old_price: "78.23",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["black", "gray", "blue"],
    gender: "men",
  },
  {
    id: 4,
    name: "Daily Ritual Women's High-Rise Skinny Jean",
    price: "48.14",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/81RDUDeClLL._AC_UL320_.jpg",
        color: "gray",
      },
      {
        image: "https://m.media-amazon.com/images/I/81UwxTpG-oL._AC_UL320_.jpg",
        color: "blue",
      },
      {
        image: "https://m.media-amazon.com/images/I/71ImcTG+wAL._AC_UL320_.jpg",
        color: "black",
      },
    ],
    solde: true,
    old_price: "143",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["gray", "blue", "black"],
    gender: "women",
  },
  {
    id: 5,
    name: "American Apparel Women's High-Waist Jean",
    price: "123",
    images: [
      {
        image: "https://m.media-amazon.com/images/I/71y6LE5Xp-L._AC_UL320_.jpg",
        color: "blue",
      },
    ],
    solde: false,
    old_price: "",
    sizes: [
      "24(00) Short",
      "25(0) Short",
      "26(2) Short",
      "27(4) Short",
      "28(6) Short",
      "29(8) Short",
      "30(10) Short",
      "31(12) Short",
      "32(14) Short",
      "24(00) Regular",
      "24(00) Long",
      "25(0) Regular",
      "25(0) Long",
      "26(2) Regular",
      "26(2) Long",
      "27(4) Regular",
      "27(4) Long",
      "28(6) Regular",
      "28(6) Long",
      "29(8) Regular",
      "30(10) Regular"
    ],
    colors: ["blue"],
    gender: "women",
  },
];

export default jeans;
