// CART ACTIONS
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

// USER ACTIONS
const SET_USER = 'SET_USER';

export {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  SET_USER,
};
